name: menejemen_waktu
description: 'A new Flutter project.'
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  animate_do: ^3.3.4
  animated_bottom_navigation_bar: ^1.3.3
  awesome_notifications: any
  awesome_notifications_core: ^0.9.3
  crypto: ^3.0.3
  cupertino_icons: ^1.0.6
  date_picker_plus: ^4.0.0
  date_picker_timeline: ^1.2.6
  firebase_auth: ^5.0.0
  firebase_core: ^3.0.0
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.1.2
  flutter_native_splash: ^2.4.0
  flutter_native_timezone_updated_gradle: ^2.0.3
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  get: ^4.6.6
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  image_picker: ^1.1.1
  intl: ^0.19.0
  mat_month_picker_dialog: ^1.1.2
  package_info_plus: ^8.0.0
  path: ^1.9.0
  path_provider: ^2.0.11
  provider: ^6.1.2
  rxdart: ^0.27.7
  salomon_bottom_bar: ^3.3.2
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3+1
  timeline_tile: ^2.0.0
  timezone: ^0.9.3

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/loading/

  fonts:
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/SF/Display/SF-Pro-Display-Regular.ttf
        - asset: assets/fonts/SF/Display/SF-Pro-Display-SemiBold.ttf
          weight: 600
